#!/bin/sh

SEMAGROW_SHORT_NAME="${distribution.all.package.shortname}";
SEMAGROW_HOME="${distribution.all.package.home}";
SEMAGROW_GROUP="${distribution.all.package.group}";
SEMAGROW_USER="${distribution.all.package.user}";

echo "POSTINSTALL (version: ${project.version}) WITH $@"

set -e
case "$1" in
    configure)
				echo "Configure";
        chmod 640 $SEMAGROW_HOME/conf/tomcat-users.xml
        chown -Rh $SEMAGROW_USER:$SEMAGROW_GROUP $SEMAGROW_HOME
        chown -Rh $SEMAGROW_USER:$SEMAGROW_GROUP /var/log/$SEMAGROW_SHORT_NAME
        chown -Rh $SEMAGROW_USER:$SEMAGROW_GROUP /var/lib/$SEMAGROW_SHORT_NAME
        chmod +x  $SEMAGROW_HOME/bin/*.sh        
        chmod +x  /etc/init.d/$SEMAGROW_SHORT_NAME
    ;;
		abort-remove)
			echo "Abort remove";
		;;
		abort-upgrade)
			echo "Abort upgrade";
		;;
esac
